const List<Map<String, String>> allCities = [
  {'display': 'Hà Nội', 'api': 'Hanoi'},
  {'display': 'Hồ Chí Minh', 'api': 'Ho Chi Minh City'},
  {'display': 'Đà Nẵng', 'api': 'Turan'},
  {'display': 'Hải Phòng', 'api': 'Haiphong'},
  {'display': 'Cần Thơ', 'api': 'Can Tho'},
  {'display': 'Nha Trang', 'api': 'Nha Trang'},
  {'display': 'Huế', 'api': 'Hue'},
  {'display': 'Vũng Tàu', 'api': 'Vung Tau'},
  {'display': 'Biên Hòa', 'api': 'Bien Hoa'},
  {'display': 'Buôn Ma Thuột', 'api': 'Buon Ma Thuot'},
  {'display': 'Pleiku', 'api': 'Pleiku'},
  {'display': 'Đà Lạt', 'api': 'Da Lat'},
  {'display': 'Quy Nhơn', 'api': 'Quy Nhon'},
  {'display': 'Phan Thiết', 'api': 'Phan Thiet'},
  {'display': 'Long Xuyên', 'api': 'Long Xuyen'},
  {'display': 'Rạch Giá', 'api': 'Rach Gia'},
  {'display': 'Cà Mau', 'api': 'Ca Mau'},
  {'display': 'Vinh', 'api': 'Vinh'},
  {'display': 'Thanh Hóa', 'api': 'Thanh Hoa'},
  {'display': 'Nam Định', 'api': 'Nam Dinh'},
  {'display': 'Thái Nguyên', 'api': 'Thai Nguyen'},
  {'display': 'Hạ Long', 'api': 'Ha Long'},
  {'display': 'Uông Bí', 'api': 'Uong Bi'},
  {'display': 'Lào Cai', 'api': 'Lao Cai'},
  {'display': 'Sơn La', 'api': 'Son La'},
  {'display': 'Điện Biên Phủ', 'api': 'Dien Bien Phu'},
  {'display': 'Lạng Sơn', 'api': 'Lang Son'},
  {'display': 'Bắc Ninh', 'api': 'Bac Ninh'},
  {'display': 'Bắc Giang', 'api': 'Bac Giang'},
  {'display': 'Hưng Yên', 'api': 'Hung Yen'},
];
